---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: yamaszone/php7-lumen:7.1-fpm-alpine
        ports:
        - containerPort: 9000
        env:
          - name: DB_CONNECTION
            value: pgsql
          - name: DB_HOST
            value: postgres
          - name: DB_PORT
            value: "5432"
          - name: DB_DATABASE
            value: lumen_db
          - name: DB_USERNAME
            value: lumen
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pgpass
                key: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: yamaszone/nginx:1.13-alpine
        ports:
        - containerPort: 80
